project:
  type: website
  output-dir: docs

website:
  title: "Allison Payne"
  navbar:
    left:
      - projects.qmd
      - pubs.qmd

format:
  html:
    theme: 
      - custom.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    page-layout: full

editor: visual

