project:
  type: website

website:
  title: "Allison Payne"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pubs.qmd
      - projects.qmd

format:
  html:
    theme: 
      - custom.scss
    mainfont: Quicksand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

