project:
  type: website

website:
  title: "Allison Payne"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - pubs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

