---
title: "Research interests"
toc: false 
---

As a lifelong lover of the ocean, I have always been curious about deep sea ecosystems. Through the course of my PhD, I have become interested in how long-term ecological research, open science practices, and inclusive research and pedagogy can all contribute to more impactful and equitable discoveries in the deep sea.

## Long term studies

Long-term studies can help answer pressing ecological questions while simultaneously creating research opportunities for early-career ecologists. I have enjoyed teaching and mentoring undergraduates as a field leader at Año Nuevo State Park for the Beltran lab's field assistant program. I have also been an instructor and TA for *Field Methods for Large Marine Vertebrates,* in which I help guide undergraduates through the scientific process from formulating questions, to collecting data, to publishing the results. So far, I have worked on two manuscripts from these classes, including my dissertation chapter on reproductive senescence in elephant seals.

**Selected work:**

[*Reproductive success and offspring survival decline for female elephant seals past prime age*](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.14226)*, Journal of Animal Ecology, 2024*

[*Elephant seals as ecosystem sentinels for the northeast Pacific Ocean twilight zone*](https://www.science.org/doi/10.1126/science.adp2244)*, Science, 2025*

[*Long-term studies should provide structure for inclusive education and professional development*](https://doi.org/10.1111/ele.14482)*, Ecology Letters, 2025*

## Open science

I am also interested in the process of scientific discovery. Whether it's using science facilitation practices to help research teams create new knowledge, documenting the use of open science tools, or distilling best practices from an ecological sub-field, I am curious about the people, practices, and tools that make science happen.

**Selected projects:**

[*Minimum reporting standards can promote animal welfare and data quality in biologging research*](https://ecoevorxiv.org/repository/view/6784/)*, EcoEvoRxiv*

[*EcoViz + AI Workshop Science Facilitator*](https://harmless-dolomite-426.notion.site/ac0866fc656441d7a26c071ad528ed15?v=8f6278b036774b7b86e969dbc31e3de4)

[*Open Biologging Project*](https://flukeandfeather.github.io/openbiologging/)

## Inclusive research practices

I believe scientists should think deeply not only about their research questions, but also about how their research is done. I'm passionate about creating more inclusive research environments and have worked in particular on several projects to improve the safety of LGBTQ+ scientists.

**Selected projects:**

[*Queer Ecologies*](https://allisonpayne.github.io/queerecologies/)*, an undergraduate course in Ecology and Evolutionary Biology*

[*Queer & Trans Inclusive Field Summit*](https://jasper-cat-921.notion.site/43bde69971c8403d91cb2f9a4fb18e75?v=16b6c3408d514d34ada36ebf36d1db99)*, founder and facilitator*

[*Oceanography's Diversity Deficit: Identifying and addressing challenges for marginalized groups*](https://tos.org/oceanography/assets/docs/36-4-payne.pdf)*, Oceanography, 2023*
